various new feaures...
Store state as string instead of object (breaking)
Add generic template method and change Bubble format  (breaking)
UnexpectedInputError: message is optional and it can now stop repeating
of quick replies
User babel target setting